// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: chameleon/agentd/proto/chameleon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionResponse_Action int32

const (
	DecisionResponse_PASS    DecisionResponse_Action = 0
	DecisionResponse_DECEIVE DecisionResponse_Action = 1
	DecisionResponse_TARPIT  DecisionResponse_Action = 2 // Explicit action for just delay
)

// Enum value maps for DecisionResponse_Action.
var (
	DecisionResponse_Action_name = map[int32]string{
		0: "PASS",
		1: "DECEIVE",
		2: "TARPIT",
	}
	DecisionResponse_Action_value = map[string]int32{
		"PASS":    0,
		"DECEIVE": 1,
		"TARPIT":  2,
	}
)

func (x DecisionResponse_Action) Enum() *DecisionResponse_Action {
	p := new(DecisionResponse_Action)
	*p = x
	return p
}

func (x DecisionResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_chameleon_agentd_proto_chameleon_proto_enumTypes[0].Descriptor()
}

func (DecisionResponse_Action) Type() protoreflect.EnumType {
	return &file_chameleon_agentd_proto_chameleon_proto_enumTypes[0]
}

func (x DecisionResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionResponse_Action.Descriptor instead.
func (DecisionResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_chameleon_agentd_proto_chameleon_proto_rawDescGZIP(), []int{1, 0}
}

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         string                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Added headers for completeness
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_chameleon_agentd_proto_chameleon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chameleon_agentd_proto_chameleon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_chameleon_agentd_proto_chameleon_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *ClassifyRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ClassifyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ClassifyRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ClassifyRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type DecisionResponse struct {
	state      protoimpl.MessageState  `protogen:"open.v1"`
	Action     DecisionResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=chameleon.DecisionResponse_Action" json:"action,omitempty"`
	Message    string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                 // The deception body (HTML/JSON)
	DelayMs    int32                   `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"` // Tarpit delay
	Label      string                  `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`                     // ML/Rule label (e.g., "sqli")
	Confidence float64                 `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`         // 0.0 - 1.0
	// Honeypot details
	HoneypotHost  string `protobuf:"bytes,6,opt,name=honeypot_host,json=honeypotHost,proto3" json:"honeypot_host,omitempty"`
	HoneypotPort  int32  `protobuf:"varint,7,opt,name=honeypot_port,json=honeypotPort,proto3" json:"honeypot_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_chameleon_agentd_proto_chameleon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chameleon_agentd_proto_chameleon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_chameleon_agentd_proto_chameleon_proto_rawDescGZIP(), []int{1}
}

func (x *DecisionResponse) GetAction() DecisionResponse_Action {
	if x != nil {
		return x.Action
	}
	return DecisionResponse_PASS
}

func (x *DecisionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DecisionResponse) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *DecisionResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DecisionResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DecisionResponse) GetHoneypotHost() string {
	if x != nil {
		return x.HoneypotHost
	}
	return ""
}

func (x *DecisionResponse) GetHoneypotPort() int32 {
	if x != nil {
		return x.HoneypotPort
	}
	return 0
}

var File_chameleon_agentd_proto_chameleon_proto protoreflect.FileDescriptor

const file_chameleon_agentd_proto_chameleon_proto_rawDesc = "" +
	"\n" +
	"&chameleon/agentd/proto/chameleon.proto\x12\tchameleon\"\xe7\x01\n" +
	"\x0fClassifyRequest\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\tR\x05srcIp\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12A\n" +
	"\aheaders\x18\x05 \x03(\v2'.chameleon.ClassifyRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x02\n" +
	"\x10DecisionResponse\x12:\n" +
	"\x06action\x18\x01 \x01(\x0e2\".chameleon.DecisionResponse.ActionR\x06action\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bdelay_ms\x18\x03 \x01(\x05R\adelayMs\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\rhoneypot_host\x18\x06 \x01(\tR\fhoneypotHost\x12#\n" +
	"\rhoneypot_port\x18\a \x01(\x05R\fhoneypotPort\"+\n" +
	"\x06Action\x12\b\n" +
	"\x04PASS\x10\x00\x12\v\n" +
	"\aDECEIVE\x10\x01\x12\n" +
	"\n" +
	"\x06TARPIT\x10\x022P\n" +
	"\tChameleon\x12C\n" +
	"\bClassify\x12\x1a.chameleon.ClassifyRequest\x1a\x1b.chameleon.DecisionResponseB2Z0github.com/awwyushh/chameleon/agentd/proto;protob\x06proto3"

var (
	file_chameleon_agentd_proto_chameleon_proto_rawDescOnce sync.Once
	file_chameleon_agentd_proto_chameleon_proto_rawDescData []byte
)

func file_chameleon_agentd_proto_chameleon_proto_rawDescGZIP() []byte {
	file_chameleon_agentd_proto_chameleon_proto_rawDescOnce.Do(func() {
		file_chameleon_agentd_proto_chameleon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chameleon_agentd_proto_chameleon_proto_rawDesc), len(file_chameleon_agentd_proto_chameleon_proto_rawDesc)))
	})
	return file_chameleon_agentd_proto_chameleon_proto_rawDescData
}

var file_chameleon_agentd_proto_chameleon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chameleon_agentd_proto_chameleon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chameleon_agentd_proto_chameleon_proto_goTypes = []any{
	(DecisionResponse_Action)(0), // 0: chameleon.DecisionResponse.Action
	(*ClassifyRequest)(nil),      // 1: chameleon.ClassifyRequest
	(*DecisionResponse)(nil),     // 2: chameleon.DecisionResponse
	nil,                          // 3: chameleon.ClassifyRequest.HeadersEntry
}
var file_chameleon_agentd_proto_chameleon_proto_depIdxs = []int32{
	3, // 0: chameleon.ClassifyRequest.headers:type_name -> chameleon.ClassifyRequest.HeadersEntry
	0, // 1: chameleon.DecisionResponse.action:type_name -> chameleon.DecisionResponse.Action
	1, // 2: chameleon.Chameleon.Classify:input_type -> chameleon.ClassifyRequest
	2, // 3: chameleon.Chameleon.Classify:output_type -> chameleon.DecisionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chameleon_agentd_proto_chameleon_proto_init() }
func file_chameleon_agentd_proto_chameleon_proto_init() {
	if File_chameleon_agentd_proto_chameleon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chameleon_agentd_proto_chameleon_proto_rawDesc), len(file_chameleon_agentd_proto_chameleon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chameleon_agentd_proto_chameleon_proto_goTypes,
		DependencyIndexes: file_chameleon_agentd_proto_chameleon_proto_depIdxs,
		EnumInfos:         file_chameleon_agentd_proto_chameleon_proto_enumTypes,
		MessageInfos:      file_chameleon_agentd_proto_chameleon_proto_msgTypes,
	}.Build()
	File_chameleon_agentd_proto_chameleon_proto = out.File
	file_chameleon_agentd_proto_chameleon_proto_goTypes = nil
	file_chameleon_agentd_proto_chameleon_proto_depIdxs = nil
}
