// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: chameleon/agentd/proto/chameleon.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chameleon_Classify_FullMethodName = "/chameleon.Chameleon/Classify"
)

// ChameleonClient is the client API for Chameleon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChameleonClient interface {
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
}

type chameleonClient struct {
	cc grpc.ClientConnInterface
}

func NewChameleonClient(cc grpc.ClientConnInterface) ChameleonClient {
	return &chameleonClient{cc}
}

func (c *chameleonClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, Chameleon_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChameleonServer is the server API for Chameleon service.
// All implementations must embed UnimplementedChameleonServer
// for forward compatibility.
type ChameleonServer interface {
	Classify(context.Context, *ClassifyRequest) (*DecisionResponse, error)
	mustEmbedUnimplementedChameleonServer()
}

// UnimplementedChameleonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChameleonServer struct{}

func (UnimplementedChameleonServer) Classify(context.Context, *ClassifyRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedChameleonServer) mustEmbedUnimplementedChameleonServer() {}
func (UnimplementedChameleonServer) testEmbeddedByValue()                   {}

// UnsafeChameleonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChameleonServer will
// result in compilation errors.
type UnsafeChameleonServer interface {
	mustEmbedUnimplementedChameleonServer()
}

func RegisterChameleonServer(s grpc.ServiceRegistrar, srv ChameleonServer) {
	// If the following call pancis, it indicates UnimplementedChameleonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chameleon_ServiceDesc, srv)
}

func _Chameleon_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChameleonServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chameleon_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChameleonServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chameleon_ServiceDesc is the grpc.ServiceDesc for Chameleon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chameleon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chameleon.Chameleon",
	HandlerType: (*ChameleonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _Chameleon_Classify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chameleon/agentd/proto/chameleon.proto",
}
